In [3]:
#lets install lhe selenium libariries
!pip install selenium

Requirement already satisfied: selenium in c:\users\inpshy\anaconda3\lib\site-packages (3.141.0)
Requirement already satisfied: urllib3 in c:\users\inpshy\anaconda3\lib\site-packages (from selenium) (1.25.11)

In [4]:
# Importing Libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

# Importing selenium webdriver 
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException,ElementNotInteractableException

#Importing requests
import requests

# importing regex
import re
import urllib3

In [3]:
# Question no1 Youtube lets first connect with webdriver
driver=webdriver.Chrome(r"C:\Users\INPshy\Downloads\chromedriver_win32\chromedriver.exe")

In [112]:
#URL Link
url='https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos/'
driver.get(url)   
time.sleep(2)

In [113]:
correct_name=driver.find_element_by_xpath('//a[@class="external text"]')
correct_name.click()
time.sleep(2)

In [114]:
list=driver.find_element_by_xpath('//div[@class="mw-search-result-heading"]')
list.click()
time.sleep(2)

In [115]:
#create empty list to store
Rank=[]
Name=[]
Artist=[]
Date=[]
Views=[]

In [116]:

#fetch Rank
try:
    rank=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[1]")
    for i in rank:
        Rank.append(i.text)
except NoSuchElementException: 
    
    Rank.append('-')
#fetch Name
try:
    name=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[2]")
    for j in name:
        Name.append(j.text)
except NoSuchElementException:
    Name.append('-')
#fetch Artist
try:
    artist=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[3]")
    for k in artist:
        Artist.append(k.text)
except NoSuchElementException:
    Artist.append('-')
#fetch DAte
try:
    date=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[5]")
    for l in date:
        Date.append(l.text)
except NoSuchElementException:
    Date.append('-')
    
#fetch Views
try:
    view=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[4]")
    for m in view:
        Views.append(m.text)
except NoSuchElementException:
    Views.append('-')

In [121]:
Top_video=pd.DataFrame({})
Top_video['Rank']=Rank[:30]
Top_video['Video Name']=Name[:30]
Top_video['Artist']=Artist[:30]
Top_video['Views']=Views[:30]
Top_video['Date']=Date[:30]
Top_video

,Rank,Video Name,Artist,Views,Date
0,1.,"""Baby Shark Dance""[22]",Pinkfong Kids' Songs & Stories,9.04,"June 17, 2016"
1,2.,"""Despacito""[24]",Luis Fonsi,7.46,"January 12, 2017"
2,3.,"""Johny Johny Yes Papa""[25]",LooLoo Kids,5.58,"October 8, 2016"
3,4.,"""Shape of You""[26]",Ed Sheeran,5.40,"January 30, 2017"
4,5.,"""See You Again""[27]",Wiz Khalifa,5.19,"April 6, 2015"
5,6.,"""Masha and the Bear – Recipe for Disaster""[30]",Get Movies,4.45,"January 31, 2012"
6,7.,"""Bath Song""[31]",Cocomelon – Nursery Rhymes,4.37,"May 2, 2018"
7,8.,"""Learning Colors – Colorful Eggs on a Farm""[32]",Miroshka TV,4.31,"February 27, 2018"
8,9.,"""Uptown Funk""[33]",Mark Ronson,4.24,"November 19, 2014"
9,10.,"""Gangnam Style""[34]",Psy,4.13,"July 15, 2012"
10,11.,"""Phonics Song with Two Words""[36]",ChuChu TV,4.02,"March 6, 2014"
11,12.,"""Sugar""[37]",Maroon 5,3.51,"January 14, 2015"
12,13.,"""Dame Tu Cosita""[38]",El Chombo,3.48,"April 5, 2018"
13,14.,"""Sorry""[39]",Justin Bieber,3.45,"October 22, 2015"
14,15.,"""Roar""[40]",Katy Perry,3.39,"September 5, 2013"
15,16.,"""Counting Stars""[41]",OneRepublic,3.35,"May 31, 2013"
16,17.,"""Thinking Out Loud""[42]",Ed Sheeran,3.29,"October 7, 2014"
17,18.,"""Wheels on the Bus""[43]",Cocomelon – Nursery Rhymes,3.18,"May 24, 2018"
18,19.,"""Dark Horse""[44]",Katy Perry,3.11,"February 20, 2014"
19,20.,"""Faded""[45]",Alan Walker,3.10,"December 3, 2015"
20,21.,"""Shake It Off""[46]",Taylor Swift,3.08,"August 18, 2014"
21,22.,"""Girls Like You""[47]",Maroon 5,3.08,"May 31, 2018"
22,23.,"""Lean On""[48]",Major Lazer,3.07,"March 22, 2015"
23,24.,"""Bailando""[49]",Enrique Iglesias,3.07,"April 11, 2014"
24,25.,"""Let Her Go""[50]",Passenger,3.03,"July 25, 2012"
25,26.,"""Mi Gente""[51]",J Balvin,2.95,"June 29, 2017"
26,27.,"""Perfect""[52]",Ed Sheeran,2.90,"November 9, 2017"
27,28.,"""Axel F""[53]",Crazy Frog,2.90,"June 16, 2009"
28,29.,"""Waka Waka (This Time for Africa)""[54]",Shakira,2.89,"June 4, 2010"
29,30.,"""Hello""[55]",Adele,2.86,"October 22, 2015"

In [5]:
# Question no2 BCCI lets first connect with webdriver
driver=webdriver.Chrome(r"C:\Users\INPshy\Downloads\chromedriver_win32\chromedriver.exe")

In [6]:
Url = 'https://www.bcci.tv/'
driver.get(Url)

In [7]:
button=driver.find_element_by_xpath('//button[@class="slider__chev js-prev"]')
button.click()

In [21]:
#going to international fixtures page

fixtures=driver.find_element_by_xpath("//div[@class='navigation__drop-down drop-down drop-down--reveal-on-hover']/div/ul/li/a")

try:

    fixtures.click()

except ElementNotInteractableException:

    driver.get(fixtures.get_attribute('href'))

In [22]:
Match_title=[]
Series=[]
Place=[]
Date=[]
Time=[]

In [23]:
#fetch Match
try:
    match_title=driver.find_elements_by_xpath('//p[@class="fixture__additional-info"]/strong')
    for i in match_title:
        Match_title.append(i.text)
except NoSuchElementException:
    Match_title.append('-')

In [24]:
Match_title

['1st Test', '2nd Test', '3rd Test', '4th Test', '5th Test']

In [25]:
#fetch Series
try:
    series=driver.find_elements_by_xpath('//div[@class="fixture__format-strip"]/span[2]')
    for i in series:
        Series.append(i.text)
except NoSuchElementException: 
    Series.append('-')

In [26]:
Series

['ENGLAND V INDIA 2021',
 'ENGLAND V INDIA 2021',
 'ENGLAND V INDIA 2021',
 'ENGLAND V INDIA 2021',
 'ENGLAND V INDIA 2021']

In [27]:
#fetch Location
try:
    location=driver.find_elements_by_xpath('//p[@class="fixture__additional-info"]/span')
    for i in location:
        Place.append(i.text)
except NoSuchElementException:
    Place.append('-')
Place

['Trent Bridge, Nottingham',
 "Lord's, London",
 'Headingley, Leeds',
 'The Oval, London',
 'Old Trafford, Manchester']

In [28]:
#fetch date
try:
    date=driver.find_elements_by_xpath('//span[@class="fixture__date"]')
    for i in date:
        Date.append(i.text)
except NoSuchElementException:
    Date.append('-')
Date

['04', '12', '25', '02', '10']

In [29]:
#fetch Time
try:
    time=driver.find_elements_by_xpath('//span[@class="fixture__time"]')
    for i in time:
        Time.append(i.text)   
except NoSuchElementException:
    Time.append('-')
Time

['15:30 IST', '15:30 IST', '15:30 IST', '15:30 IST', '15:30 IST']

In [30]:
Match=pd.DataFrame({})
Match['Match Title']=Match_title[:5]
Match['Series']=Series[:5]
Match['Place']=Place[:5]
Match['Date']=Date[:5]
Match['Time']=Time[:5]
Match

  Match Title                Series                     Place Date       Time
0    1st Test  ENGLAND V INDIA 2021  Trent Bridge, Nottingham   04  15:30 IST
1    2nd Test  ENGLAND V INDIA 2021            Lord's, London   12  15:30 IST
2    3rd Test  ENGLAND V INDIA 2021         Headingley, Leeds   25  15:30 IST
3    4th Test  ENGLAND V INDIA 2021          The Oval, London   02  15:30 IST
4    5th Test  ENGLAND V INDIA 2021  Old Trafford, Manchester   10  15:30 IST

In [51]:
# Question no3 Guru99 lets first connect with webdriver
driver=webdriver.Chrome(r"C:\Users\INPshy\Downloads\chromedriver_win32\chromedriver.exe")

In [52]:
url='https://www.guru99.com/'
driver.get(url)

In [53]:
#going to selenium page

selenium=driver.find_element_by_xpath("//ul[@class='menu']/li[3]/a")

try:

    selenium.click()

except ElementNotInteractableException:

    driver.get(selenium.get_attribute('href'))

In [55]:
#going to exception handling page
exception=driver.find_element_by_xpath('/html/body/div[2]/section[3]/div/div[1]/main/div/div/div/div/div/div/div[2]/table[5]/tbody/tr[34]/td[1]')
try:
    exception.click()
except ElementNotInteractableException:
    
    driver.get(exception.get_attribute('href'))

In [56]:
Name=[]
Description=[]

In [57]:
# fetch Name 
try:
    name=driver.find_elements_by_xpath('//table[@class="table table-striped"]/tbody/tr/td[1]')
    for i in name:
        Name.append(i.text)
except NoSuchElementException:
    Name.append('-')

In [58]:
len(Name)

42

In [59]:
# fetch Description 
try:
    description=driver.find_elements_by_xpath('//table[@class="table table-striped"]/tbody/tr/td[2]')
    for i in description:
        Description.append(i.text)
except NoSuchElementException:
    Description.append('-')
len(Description)

42

In [62]:
Selenium=pd.DataFrame({})
Selenium['Name']=Name[:42]
Selenium['Description']=Description[:42]
Selenium

,Name,Description
0,Exception name,Description
1,ElementNotVisibleException,This type of Selenium exception occurs when an...
2,ElementNotSelectableException,This Selenium exception occurs when an element...
3,NoSuchElementException,This Exception occurs if an element could not ...
4,NoSuchFrameException,This Exception occurs if the frame target to b...
5,NoAlertPresentException,This Exception occurs when you switch to no pr...
6,NoSuchWindowException,This Exception occurs if the window target to ...
7,StaleElementReferenceException,This Selenium exception occurs happens when th...
8,SessionNotFoundException,The WebDriver is acting after you quit the bro...
9,TimeoutException,Thrown when there is not enough time for a com...
10,WebDriverException,This Exception takes place when the WebDriver ...
11,ConnectionClosedException,This type of Exception takes place when there ...
12,ElementClickInterceptedException,The command may not be completed as the elemen...
13,ElementNotInteractableException,This Selenium exception is thrown when any ele...
14,ErrorInResponseException,This happens while interacting with the Firefo...
15,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
16,ImeActivationFailedException,This expectation will occur when IME engine ac...
17,ImeNotAvailableException,It takes place when IME support is unavailable.
18,InsecureCertificateException,Navigation made the user agent to hit a certif...
19,InvalidArgumentException,It occurs when an argument does not belong to ...
20,InvalidCookieDomainException,This happens when you try to add a cookie unde...
21,InvalidCoordinatesException,This type of Exception matches an interacting ...
22,InvalidElementStateExceptio,It occurs when command can't be finished when ...
23,InvalidSessionIdException,This Exception took place when the given sessi...
24,InvalidSwitchToTargetException,This occurs when the frame or window target to...
25,JavascriptException,This issue occurs while executing JavaScript g...
26,JsonException,It occurs when you afford to get the session w...
27,NoSuchAttributeException,This kind of Exception occurs when the attribu...
28,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
29,NoSuchContextException,ContextAware does mobile device testing.
30,NoSuchCookieException,This Exception occurs when no cookie matching ...
31,NotFoundException,This Exception is a subclass of WebDriverExcep...
32,RemoteDriverServerException,This Selenium exception is thrown when the ser...
33,ScreenshotException,It is not possible to capture a screen.
34,SessionNotCreatedException,It happens when a new session could not be suc...
35,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
36,UnexpectedTagNameException,Happens if a support class did not get a web e...
37,UnhandledAlertException,This expectation occurs when there is an alert...
38,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
39,UnknownMethodException,This Exception happens when the requested comm...
40,UnreachableBrowserException,This Exception occurs only when the browser is...
41,UnsupportedCommandException,This occurs when remote WebDriver does n't sen...

In [63]:
# Question no4 statewise GDP lets first connect with webdriver
driver=webdriver.Chrome(r"C:\Users\INPshy\Downloads\chromedriver_win32\chromedriver.exe")

In [64]:
url='http://statisticstimes.com/'
driver.get(url)

In [69]:
#going to stats economy 
economy=driver.find_element_by_xpath('/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]')
try:
    economy.click()
except ElementNotInteractableException:
    
    driver.get(economy.get_attribute('href'))

In [70]:
click=driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
click.click()

In [ ]:
Rank=[]
State=[]
GSDP_19_20=[]
GSDP_18_19=[]
Share=[]
GDP_billion=[]

In [72]:
#fetch Rank
try:
    rank=driver.find_elements_by_xpath('//table[@class="/html/body/div[2]/div[2]/div[2]/ul/li[1]/a"]/tbody/tr/td[1]')
    for i in rank:
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append('-')
Rank

['1',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33']

In [73]:
#fetch State
try:
    state=driver.find_elements_by_xpath('//table[@class="/html/body/div[2]/div[2]/div[2]/ul/li[1]/a"]/tbody/tr/td[2]')
    for i in state:
        State.append(i.text)
except NoSuchElementException:
    State.append('-')
State

['Maharashtra',
 'Tamil Nadu',
 'Uttar Pradesh',
 'Gujarat',
 'Karnataka',
 'West Bengal',
 'Rajasthan',
 'Andhra Pradesh',
 'Telangana',
 'Madhya Pradesh',
 'Kerala',
 'Delhi',
 'Haryana',
 'Bihar',
 'Punjab',
 'Odisha',
 'Assam',
 'Chhattisgarh',
 'Jharkhand',
 'Uttarakhand',
 'Jammu & Kashmir',
 'Himachal Pradesh',
 'Goa',
 'Tripura',
 'Chandigarh',
 'Puducherry',
 'Meghalaya',
 'Sikkim',
 'Manipur',
 'Nagaland',
 'Arunachal Pradesh',
 'Mizoram',
 'Andaman & Nicobar Islands']

In [74]:
len(State)

33

In [75]:
#fetch GSDP_19_20
try:
    gsdp=driver.find_elements_by_xpath('//table[@class="/html/body/div[2]/div[2]/div[2]/ul/li[1]/a"]/tbody/tr/td[3]')
    for i in gsdp:
        GSDP_19_20.append(i.text)
except NoSuchElementException:
    GSDP_19_20.append('-')
GSDP_19_20

['-',
 '1,845,853',
 '1,687,818',
 '-',
 '1,631,977',
 '1,253,832',
 '1,020,989',
 '972,782',
 '969,604',
 '906,672',
 '-',
 '856,112',
 '831,610',
 '611,804',
 '574,760',
 '521,275',
 '-',
 '329,180',
 '328,598',
 '-',
 '-',
 '165,472',
 '80,449',
 '55,984',
 '-',
 '38,253',
 '36,572',
 '32,496',
 '31,790',
 '-',
 '-',
 '26,503',
 '-']

In [76]:
len(GSDP_19_20)

33

In [77]:
#fetch GSDP_18_19
try:
    gsdp_18=driver.find_elements_by_xpath('//table[@class="/html/body/div[2]/div[2]/div[2]/ul/li[1]/a"]/tbody/tr/td[4]')
    for i in gsdp_18:
        GSDP_18_19.append(i.text)
except NoSuchElementException:
    GSDP_18_19.append('-')
GSDP_18_19

['2,632,792',
 '1,630,208',
 '1,584,764',
 '1,502,899',
 '1,493,127',
 '1,089,898',
 '942,586',
 '862,957',
 '861,031',
 '809,592',
 '781,653',
 '774,870',
 '734,163',
 '530,363',
 '526,376',
 '487,805',
 '315,881',
 '304,063',
 '297,204',
 '245,895',
 '155,956',
 '153,845',
 '73,170',
 '49,845',
 '42,114',
 '34,433',
 '33,481',
 '28,723',
 '27,870',
 '27,283',
 '24,603',
 '22,287',
 '-']

In [78]:
#fetch Share
try:
    share=driver.find_elements_by_xpath('//table[@class="/html/body/div[2]/div[2]/div[2]/ul/li[1]/a"]/tbody/tr/td[5]')
    for i in share:
        Share.append(i.text)
except NoSuchElementException:
    Share.append('-')
Share

['13.94%',
 '8.63%',
 '8.39%',
 '7.96%',
 '7.91%',
 '5.77%',
 '4.99%',
 '4.57%',
 '4.56%',
 '4.29%',
 '4.14%',
 '4.10%',
 '3.89%',
 '2.81%',
 '2.79%',
 '2.58%',
 '1.67%',
 '1.61%',
 '1.57%',
 '1.30%',
 '0.83%',
 '0.81%',
 '0.39%',
 '0.26%',
 '0.22%',
 '0.18%',
 '0.18%',
 '0.15%',
 '0.15%',
 '0.14%',
 '0.13%',
 '0.12%',
 '-']

In [79]:
#fetch GDP
try:
    gdp=driver.find_elements_by_xpath('//table[@class="/html/body/div[2]/div[2]/div[2]/ul/li[1]/a"]/tbody/tr/td[6]')
    for i in gdp:
        GDP_billion.append(i.text)
except NoSuchElementException:
    GDP_billion.append('-')
GDP_billion

['399.921',
 '247.629',
 '240.726',
 '228.290',
 '226.806',
 '165.556',
 '143.179',
 '131.083',
 '130.791',
 '122.977',
 '118.733',
 '117.703',
 '111.519',
 '80.562',
 '79.957',
 '74.098',
 '47.982',
 '46.187',
 '45.145',
 '37.351',
 '23.690',
 '23.369',
 '11.115',
 '7.571',
 '6.397',
 '5.230',
 '5.086',
 '4.363',
 '4.233',
 '4.144',
 '3.737',
 '3.385',
 '-']

In [80]:
len(GDP_billion)

33

In [81]:
State_GDP=pd.DataFrame({})
State_GDP['Rank']=Rank[:33]
State_GDP['State']=State[:33]
State_GDP['GSDP 19 20']=GSDP_19_20[:33]
State_GDP['GSDP 18 19']=GSDP_18_19[:33]
State_GDP['Share']=Share[:33]
State_GDP['GDP billion']=GDP_billion[:33]
State_GDP

   Rank                      State GSDP 19 20 GSDP 18 19   Share GDP billion
0     1                Maharashtra          -  2,632,792  13.94%     399.921
1     1                 Tamil Nadu  1,845,853  1,630,208   8.63%     247.629
2     2              Uttar Pradesh  1,687,818  1,584,764   8.39%     240.726
3     3                    Gujarat          -  1,502,899   7.96%     228.290
4     4                  Karnataka  1,631,977  1,493,127   7.91%     226.806
5     5                West Bengal  1,253,832  1,089,898   5.77%     165.556
6     6                  Rajasthan  1,020,989    942,586   4.99%     143.179
7     7             Andhra Pradesh    972,782    862,957   4.57%     131.083
8     8                  Telangana    969,604    861,031   4.56%     130.791
9     9             Madhya Pradesh    906,672    809,592   4.29%     122.977
10   10                     Kerala          -    781,653   4.14%     118.733
11   11                      Delhi    856,112    774,870   4.10%     117.703
12   12                    Haryana    831,610    734,163   3.89%     111.519
13   13                      Bihar    611,804    530,363   2.81%      80.562
14   14                     Punjab    574,760    526,376   2.79%      79.957
15   15                     Odisha    521,275    487,805   2.58%      74.098
16   16                      Assam          -    315,881   1.67%      47.982
17   17               Chhattisgarh    329,180    304,063   1.61%      46.187
18   18                  Jharkhand    328,598    297,204   1.57%      45.145
19   19                Uttarakhand          -    245,895   1.30%      37.351
20   20            Jammu & Kashmir          -    155,956   0.83%      23.690
21   21           Himachal Pradesh    165,472    153,845   0.81%      23.369
22   22                        Goa     80,449     73,170   0.39%      11.115
23   23                    Tripura     55,984     49,845   0.26%       7.571
24   24                 Chandigarh          -     42,114   0.22%       6.397
25   25                 Puducherry     38,253     34,433   0.18%       5.230
26   26                  Meghalaya     36,572     33,481   0.18%       5.086
27   27                     Sikkim     32,496     28,723   0.15%       4.363
28   28                    Manipur     31,790     27,870   0.15%       4.233
29   29                   Nagaland          -     27,283   0.14%       4.144
30   30          Arunachal Pradesh          -     24,603   0.13%       3.737
31   31                    Mizoram     26,503     22,287   0.12%       3.385
32   32  Andaman & Nicobar Islands          -          -       -           -

In [97]:
# Question no5 GitHub lets first connect with webdriver
driver=webdriver.Chrome(r"C:\Users\INPshy\Downloads\chromedriver_win32\chromedriver.exe")

In [98]:
url="https://github.com/"
driver.get(url)

In [99]:
button=driver.find_element_by_xpath('//button[@class="btn-link d-lg-none mt-1 js-details-target"]')
button.click()

In [100]:
explore=driver.find_element_by_xpath('/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/summary')
explore.click()

In [101]:
explore_git=driver.find_element_by_xpath('/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul[1]/li/a')
explore_git.click()
time.sleep(3)

In [102]:
trending=driver.find_element_by_xpath('/html/body/div[4]/main/div[1]/nav/div/a[3]')
trending.click()

In [103]:
#fetch url of each repository
url = []
urls = driver.find_elements_by_xpath('//h1[@class="h3 lh-condensed"]//a')
for i in urls:
    url.append(i.get_attribute("href"))
    time.sleep(2)   
url

['https://github.com/apple/swift-algorithms',
 'https://github.com/freeCodeCamp/freeCodeCamp',
 'https://github.com/SJang1/korea-covid-19-remaining-vaccine-macro',
 'https://github.com/dataease/dataease',
 'https://github.com/google/googletest',
 'https://github.com/myspaghetti/macos-virtualbox',
 'https://github.com/tailscale/tailscale',
 'https://github.com/electron/electron',
 'https://github.com/Satsuoni/widevine-l3-guesser',
 'https://github.com/jonathandata1/pegasus_spyware',
 'https://github.com/bradtraversy/50projects50days',
 'https://github.com/openai/triton',
 'https://github.com/covidpass-org/covidpass',
 'https://github.com/mschweiger/orbiter',
 'https://github.com/ed3ath/cbtracker',
 'https://github.com/521xueweihan/HelloGitHub',
 'https://github.com/xamarin/xamarin-forms-samples',
 'https://github.com/PyTorchLightning/pytorch-lightning',
 'https://github.com/google/accompanist',
 'https://github.com/rafaballerini/rafaballerini',
 'https://github.com/Anbox-halium/anbox-halium',
 'https://github.com/timb-machine/linux-malware',
 'https://github.com/pittcsc/Summer2022-Internships',
 'https://github.com/unoplatform/uno',
 'https://github.com/EbookFoundation/free-programming-books']

In [105]:
Repository_title=[]
Repository_description=[]
Contributors_count=[]
Language_used=[]

In [106]:
# scraping details from each url
for j in url:
    
    driver.get(j)
    
    try:
        repo = driver.find_element_by_xpath("/html/body/div[4]/div/main/div[1]/div[1]/div/h1")
        Repository_title.append(repo.text)
    except NoSuchElementException:
        Repository_title.append('-')
#fetch Repository Description
    try:
        descript=driver.find_element_by_xpath('/html/body/div[4]/div/main/div[2]/div/div/div[2]/div[2]/div/div[1]/div/p')
        Repository_description.append(descript.text)
    except NoSuchElementException:
        Repository_description.append('No descript')
    
    #fetch Contribution count
    try:
        contri=driver.find_element_by_xpath('/html/body/div[4]/div/main/div[2]/div/div/div[2]/div[2]/div/div[4]/div/h2/a/span')
        Contributors_count.append(contri.text)
    except NoSuchElementException:
        Contributors_count.append('No contribution')
    #fetch language
    try:
        lang=driver.find_element_by_xpath('/html/body/div[4]/div/main/div[2]/div/div/div[2]/div[2]/div/div[5]/div/ul/li/a/span[1]')
        Language_used.append(lang.text)
    except NoSuchElementException:
        Language_used.append('No title')

In [111]:
print(len(Repository_title),len(Repository_description),len(Contributors_count),len(Language_used))

25 25 25 25

In [112]:
Git_hub=pd.DataFrame({})
Git_hub['Repository_title']=Repository_title[:25]
Git_hub['Repository_Description']=Repository_description[:25]
Git_hub['Contributors']=Contributors_count[:25]
Git_hub['Language']=Language_used[:25]
Git_hub

,Repository_title,Repository_Description,Contributors,Language
0,apple\n/\nswift-algorithms,,No contribution,No title
1,freeCodeCamp\n/\nfreeCodeCamp,,"4,283",JavaScript
2,SJang1\n/\nkorea-covid-19-remaining-vaccine-macro,,No contribution,No title
3,dataease\n/\ndataease,,9,Java
4,google\n/\ngoogletest,,No contribution,No title
5,myspaghetti\n/\nmacos-virtualbox,,20,Shell
6,tailscale\n/\ntailscale,,61,Go
7,electron\n/\nelectron,,195k,No title
8,Satsuoni\n/\nwidevine-l3-guesser,No descript,No contribution,C
9,jonathandata1\n/\npegasus_spyware,,No contribution,No title
10,bradtraversy\n/\n50projects50days,,25,CSS
11,openai\n/\ntriton,,19,No title
12,covidpass-org\n/\ncovidpass,,1,No title
13,mschweiger\n/\norbiter,,2,C++
14,ed3ath\n/\ncbtracker,,6,JavaScript
15,521xueweihan\n/\nHelloGitHub,,No contribution,No title
16,xamarin\n/\nxamarin-forms-samples,,No contribution,No title
17,PyTorchLightning\n/\npytorch-lightning,,3.7k,No title
18,google\n/\naccompanist,,37,Kotlin
19,rafaballerini\n/\nrafaballerini,No descript,No contribution,No title
20,Anbox-halium\n/\nanbox-halium,No descript,4,Shell
21,timb-machine\n/\nlinux-malware,,No contribution,No title
22,pittcsc\n/\nSummer2022-Internships,,No contribution,No title
23,unoplatform\n/\nuno,,747,No title
24,EbookFoundation\n/\nfree-programming-books,,No contribution,No title

In [113]:
# Question no6 100 song from billibord, lets first connect with webdriver
driver=webdriver.Chrome(r"C:\Users\INPshy\Downloads\chromedriver_win32\chromedriver.exe")

In [147]:
url='https://www.billboard.com/'
driver.get(url)

In [148]:
button=driver.find_element_by_xpath('/html/body/div[2]/div[2]/header/button/span')
button.click()

In [149]:
#going on page top 100
try:
    top=driver.find_element_by_xpath('//li[@class="header__main-link__wrapper"]/a')
    top.click()
except ElementNotInteractableException:
    driver.get(top.get_attribute('href'))

In [150]:
hot=driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[1]/div[1]/ul/li[1]/span/span/span/span[1]/ul/li[1]/a')
hot.click()

In [152]:
Song=[]
Artist=[]
Last_week=[]
Peak_rank=[]
Weeks_on_board=[]

In [156]:
#ftech song name
try:
    name=driver.find_elements_by_xpath('//ol[@class="chart-list__elements"]/li/button/span[2]/span[1]')
    for i in name:
        Song.append(i.text)
except NoSuchElementException:
    Song.append('-')
len(Song)

300

In [157]:
#ftech Artist
try:
    artist=driver.find_elements_by_xpath('//ol[@class="chart-list__elements"]/li/button/span[2]/span[2]')
    for i in artist:
        Artist.append(i.text)
except NoSuchElementException:
    Artist.append('-')
len(Artist)

100

In [158]:
Artist

['BTS',
 'Olivia Rodrigo',
 'Dua Lipa Featuring DaBaby',
 'The Kid LAROI & Justin Bieber',
 'Doja Cat Featuring SZA',
 'Ed Sheeran',
 'BTS',
 'Lil Nas X',
 'Olivia Rodrigo',
 'The Weeknd & Ariana Grande',
 'Justin Bieber Featuring Daniel Caesar & Giveon',
 'Silk Sonic (Bruno Mars & Anderson .Paak)',
 'Polo G',
 'Normani Featuring Cardi B',
 'Walker Hayes',
 'Giveon',
 'The Weeknd',
 'Masked Wolf',
 'Doja Cat & The Weeknd',
 'The Kid LAROI',
 'Luke Combs',
 'DJ Khaled Featuring Lil Baby & Lil Durk',
 'Post Malone',
 'Marshmello X Jonas Brothers',
 'Megan Thee Stallion',
 'Nelly & Florida Georgia Line',
 'Cole Swindell',
 'Chris Young + Kane Brown',
 'Maroon 5 Featuring Megan Thee Stallion',
 'BIA Featuring Nicki Minaj',
 'Doja Cat',
 'Glass Animals',
 'Roddy Ricch',
 'Dan + Shay',
 'Maneskin',
 'Jason Aldean',
 'Chase Rice Featuring Florida Georgia Line',
 'Kali Uchis',
 'Olivia Rodrigo',
 'Saweetie Featuring Doja Cat',
 '24kGoldn Featuring iann dior',
 'Machine Gun Kelly X blackbear',
 'Olivia Rodrigo',
 'Bad Bunny',
 'Rauw Alejandro',
 'Doja Cat',
 'Drake Featuring Lil Baby',
 'Moneybagg Yo',
 'Pop Smoke Featuring Kanye West & Pusha T',
 'Trippie Redd Featuring Lil Uzi Vert',
 'Lainey Wilson',
 'Ariana Grande',
 'Miranda Lambert',
 'Pop Smoke Featuring 21 Savage & 42 Dugg',
 'Keith Urban Duet With P!nk',
 'DaBaby',
 'Duncan Laurence',
 'Ryan Hurd With Maren Morris',
 'Elle King & Miranda Lambert',
 'Regard x Troye Sivan x Tate McRae',
 'Luke Bryan',
 'AJR',
 'Dierks Bentley',
 'Pop Smoke Featuring Chris Brown',
 'Justin Moore',
 'Thomas Rhett',
 'Wizkid Featuring Tems',
 'Olivia Rodrigo',
 'J. Cole, 21 Savage & Morray',
 'Kane Brown X blackbear',
 'Pop Smoke Featuring Future',
 'Migos',
 'Nio Garcia X J Balvin X Bad Bunny',
 'Young Thug & Gunna',
 'Billie Eilish',
 'Olivia Rodrigo',
 'Rod Wave',
 'Tai Verdes',
 'DaBaby',
 'Pop Smoke',
 'Lil Baby, Lil Durk & Travis Scott',
 'Pop Smoke Featuring Rick Ross & The-Dream',
 'Blake Shelton',
 'H.E.R. Featuring Chris Brown',
 'Los Legendarios, Wisin & Jhay Cortez',
 'Pop Smoke Featuring Dua Lipa',
 'Sleepy Hallow',
 'Olivia Rodrigo',
 'Dua Lipa',
 'Old Dominion',
 'Tyler, The Creator Featuring YoungBoy Never Broke Again & Ty Dolla $ign',
 'Willow Featuring Travis Barker',
 'Aaron Lewis',
 'City Girls',
 'Elvie Shane',
 'Bella Poarch',
 'Pop Smoke Featuring Bizzy Banks',
 'Chris Stapleton',
 'Olivia Rodrigo',
 'Jameson Rodgers Featuring Luke Combs']

In [159]:
#click on last week rank
lastweek=driver.find_element_by_xpath('/html/body/main/div/div/div[6]/ul/li[3]/button')
lastweek.click()

In [160]:
#ftech last week rank
try:
    rank=driver.find_elements_by_xpath('//ol[@class="chart-list__elements"]/li/button/span[1]/span[1]')
    for i in rank:
        Last_week.append(i.text)  
except NoSuchElementException:
    Last_week.append('-')
len(Last_week)

100

In [162]:
#click on Peak rank
peak=driver.find_element_by_xpath('/html/body/main/div/div/div[6]/ul/li[4]/button')
peak.click()

In [163]:
#ftech Peak rank
try:
    peak=driver.find_elements_by_xpath('//ol[@class="chart-list__elements"]/li/button/span[1]/span[1]')
    for i in peak:
        Peak_rank.append(i.text)  
except NoSuchElementException:
    Peak_rank.append('-')
len(Peak_rank)

100

In [165]:
#click Weeks on board
peak_board=driver.find_element_by_xpath('/html/body/main/div/div/div[6]/ul/li[5]/button')
peak_board.click()

In [166]:
#ftech Weeks on board
try:
    board=driver.find_elements_by_xpath('//ol[@class="chart-list__elements"]/li/button/span[1]/span[1]')
    for i in board:
        Weeks_on_board.append(i.text)  
except NoSuchElementException:
    Weeks_on_board.append('-')
len(Weeks_on_board)

100

In [168]:
Billiboard_100=pd.DataFrame({})
Billiboard_100['Song']=Song[:100]
Billiboard_100['Artist']=Artist[:100]
Billiboard_100['Last week']=Last_week[:100]
Billiboard_100['Peak']=Peak_rank[:100]
Billiboard_100['WKS On Chart']=Weeks_on_board[:100]
Billiboard_100

,Song,Artist,Last week,Peak,WKS On Chart
0,Butter,BTS,7,1,17
1,Good 4 U,Olivia Rodrigo,2,2,41
2,Levitating,Dua Lipa Featuring DaBaby,4,7,42
3,Stay,The Kid LAROI & Justin Bieber,3,8,3
4,Kiss Me More,Doja Cat Featuring SZA,5,10,21
...,...,...,...,...,...
95,Build A Bitch,Bella Poarch,86,95,82
96,30,Pop Smoke Featuring Bizzy Banks,87,89,86
97,You Should Probably Leave,Chris Stapleton,89,98,87
98,"Jealousy, Jealousy",Olivia Rodrigo,93,100,89
99,Cold Beer Calling My Name,Jameson Rodgers Featuring Luke Combs,97,97,97

In [47]:
# Question no7 lets first connect with webdriver
driver=webdriver.Chrome(r"C:\Users\INPshy\Downloads\chromedriver_win32\chromedriver.exe")

In [48]:
url= 'https://www.naukri.com/'
driver.get(url)

In [49]:
#clicking on recuriter with title not class
recuirt=driver.find_element_by_xpath('//a[@title="Search Recruiters"]')
driver.get(recuirt.get_attribute('href'))
time.sleep(2)

In [50]:
#send data science key to search bar
search=driver.find_element_by_xpath('//input[@class="sugInp"]')
search.send_keys('Data science')

In [51]:
#click on searchbar button
button=driver.find_element_by_xpath("//button[@class='fl qsbSrch blueBtn']")
button.click()

In [52]:
Name=[]
Designation=[]
Company=[]
Skills=[]
Location=[]

In [57]:
#scarping name
try:
    name=driver.find_elements_by_xpath('//div[@class="recInfo"]/div/p/a[1]')
    for i in name:
        Name.append(i.text)
except NoSuchElementException:
    Name.append('-')
#scraping Designation
try:
    desig=driver.find_elements_by_xpath('//div[@class="recInfo"]/div/p/span[1]')
    for j in desig:  
        Designation.append(j.text)
except NoSuchElementException:
    Designation.append('NO designation')
#scraping copany name
try:
    comp=driver.find_elements_by_xpath('//div[@class="recInfo"]/div/p/a[2]')
    
    for k in comp:
        Company.append(k.text)
except NoSuchElementException:
    Company.append('No company')
#scarp skill
try:
    skill=driver.find_elements_by_xpath('//div[@class="recInfo"]/div[2]')
    for l in skill:
        Skills.append(l.text)
except NoSuchElementException:
    Skills.append('No skill')
#scrap location
try:
    location=driver.find_elements_by_xpath('//div[@class="recInfo"]/div/p/span')
    for m in location:
        Location.append(m.text)
except NoSuchElementException:
    Location.append('No location')

In [58]:
Recuirter=pd.DataFrame({})
Recuirter['Name']=Name[:50]
Recuirter['Designation']=Designation[:50]
Recuirter['Company']=Company[:50]
Recuirter['Skill']=Skills[:50]
Recuirter['Location']=Location[:50]
Recuirter

,Name,Designation,Company,Skill,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Pune
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,Chennai
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Trivandrum
8,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Indore
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Bengaluru / Bangalore
10,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Hyderabad / Secunderabad
11,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",Bengaluru / Bangalore
12,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Mumbai
13,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Pune
14,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",Hyderabad / Secunderabad
15,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Bhopal
16,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Navi Mumbai
17,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Cochin
18,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Delhi
19,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Hyderabad / Secunderabad
20,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Pune
21,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Pune
22,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Pune
23,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Pune
24,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Bengaluru / Bangalore
25,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Bengaluru / Bangalore
26,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",Delhi
27,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Bengaluru / Bangalore
28,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",Bengaluru / Bangalore
29,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",Mysoru / Mysore
30,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Bengaluru / Bangalore
31,Radha Manivasagam,HR Executive,Techcovery,"Python, Artificial Intelligence, Machine Learn...",Noida
32,Prateek Kumar,Head,Trisect,"Java, Python, Angularjs, Software Testing, Mac...",New Delhi
33,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",Chennai
34,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Aligarh
35,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Salt Lake City
36,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Pune
37,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Bengaluru / Bangalore
38,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Mumbai
39,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Indore
40,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Bengaluru / Bangalore
41,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",MYSORE
42,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",Hyderabad / Secunderabad
43,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Bengaluru / Bangalore
44,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Mumbai
45,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",Noida
46,Amir Chowdhury,Managing Partner,Granular.ai,"Machine Learning, Data Science, Product Manage...",Mumbai
47,Shailja Mishra,HR Manager,Certybox Pvt.Ltd.,"consulting, Education Counseling, Educational ...",Bengaluru / Bangalore
48,Sunny Sharma,Managing Director - HR,Western Service Providers,"Software Professionals, Engineering, Technical...",HR Manager
49,Sagar Lama,Company HR Manager,AdView,"Full Stack Developers, Product Manager, Data S...",Delhi

In [59]:
#Question no 8 The gaurdain news ,connect webdriver
driver=webdriver.Chrome(r"C:\Users\INPshy\Downloads\chromedriver_win32\chromedriver.exe")

In [63]:
Url = 'https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare'
driver.get(Url)

In [64]:
Book=[]
Author=[]
Volumes=[]
Publisher=[]
Genre=[]

In [65]:
#fetch book name
try:
    book= driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[2]')
    for i in book:
        Book.append(i.text)
except NoSuchElementException:
    Book.append('No book')
len(Book)

100

In [67]:
#fetch Author Name
try:
    author=driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[3]')
    for i in author:
        Author.append(i.text)
except NoSuchElementException:
    Author.append('No author')
len(Author)

100

In [69]:
#fetch Volumes
try:
    vol=driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[4]')
    for i in vol:
        Volumes.append(i.text)
except NoSuchElementException:
    Volumes.append('No volume')
len(Volumes)

100

In [72]:
#ftech Publisher
try:
    pub=driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[5]')
    for i in pub:
        Publisher.append(i.text)
except NoSuchElementException:
    Publisher.append('No publisher')
len(Publisher)

200

In [74]:
#ftech Gener
try:
    gen=driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[6]')
    for i in gen:
        Genre.append(i.text)
except NoSuchElementException:
    Publisher.append('No gener')
len(Genre)

100

In [75]:
Best_Novel=pd.DataFrame({})
Best_Novel['Name']=Book[:100]
Best_Novel['Author']=Author[:100]
Best_Novel['Volume']=Volumes[:100]
Best_Novel['Publisher']=Publisher[:100]
Best_Novel['Genere']=Genre[:100]
Best_Novel

,Name,Author,Volume,Publisher,Genere
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

In [149]:
# question no9 imdb most watched tv webdriver
driver=webdriver.Chrome(r"C:\Users\INPshy\Downloads\chromedriver_win32\chromedriver.exe")

In [150]:
#go to page thru Url link
Url = 'https://www.imdb.com/list/ls095964455'
driver.get(Url)

In [151]:
#create empty list to store data
Name=[]
Year=[]
Genre=[]
Run_time=[]
Ratings=[]
Votes=[]

In [152]:
#fetch name
try:
    name=driver.find_elements_by_xpath('//h3[@class="lister-item-header"]//a')
    for i in name:
        Name.append(i.text)
except NoSuchElementException:
    Name.append('No name')
len(Name)

100

In [153]:
#fetch year
try:
    year=driver.find_elements_by_xpath('//h3[@class="lister-item-header"]//span[2]')
    for i in year:
        Year.append(i.text)
except NoSuchElementException: 
    Year.append('No Year')
len(Year)

100

In [154]:
Year

['(2011–2019)',
 '(2016– )',
 '(2010–2022)',
 '(2017–2020)',
 '(2014–2020)',
 '(2013–2019)',
 '(2017– )',
 '(2005– )',
 '(2014– )',
 '(2012–2020)',
 '(2017–2021)',
 '(2007–2019)',
 '(2011– )',
 '(2010–2017)',
 '(2013–2020)',
 '(2010–2017)',
 '(2009–2017)',
 '(2011– )',
 '(2008–2013)',
 '(2016–2021)',
 '(2005–2020)',
 '(2005–2017)',
 '(2014–2020)',
 '(2011–2017)',
 '(1989– )',
 '(2011–2018)',
 '(2015–2017)',
 '(2015–2018)',
 '(1994–2004)',
 '(2005–2014)',
 '(2011–2019)',
 '(2015–2019)',
 '(2013–2018)',
 '(2015–2021)',
 '(2007–2012)',
 '(2015–2018)',
 '(2014–2019)',
 '(2016– )',
 '(2015–2019)',
 '(2009–2020)',
 '(2013– )',
 '(2016–2019)',
 '(2017–2019)',
 '(2013–2018)',
 '(2017–2020)',
 '(2018– )',
 '(2019– )',
 '(2011–2021)',
 '(2011–2018)',
 '(2013–2020)',
 '(2018– )',
 '(2006–2013)',
 '(2015– )',
 '(1999–2022)',
 '(2013– )',
 '(2004–2010)',
 '(2013– )',
 '(2004–2012)',
 '(2015–2018)',
 '(2013–2017)',
 '(2011–2020)',
 '(2015–2020)',
 '(2016– )',
 '(2017– )',
 '(2018–2020)',
 '(2017– )',
 '(2014–2019)',
 '(2009–2015)',
 '(1997– )',
 '(2013–2022)',
 '(2013–2015)',
 '(2019– )',
 '(2014–2019)',
 '(2016–2019)',
 '(2004–2012)',
 '(2015– )',
 '(2013–2017)',
 '(2017–2019)',
 '(2017–2021)',
 '(2017– )',
 '(2016–2022)',
 '(2016–2020)',
 '(2017–2018)',
 '(2018–2020)',
 '(2017–2019)',
 '(2011–2015)',
 '(2016–2018)',
 '(2012–2018)',
 '(2017)',
 '(2017–2019)',
 '(2018–2019)',
 '(2008–2015)',
 '(2016– )',
 '(2019)',
 '(2015–2019)',
 '(2013–2017)',
 '(2017–2019)',
 '(2005–2020)',
 '(2015–2019)',
 '(2018)']

In [155]:
#fetch Genre
try:
    gener=driver.find_elements_by_xpath('//p[@class="text-muted text-small"]//span[5]')
    for i in gener:
        Genre.append(i.text) 
except NoSuchElementException:
    Genre.append('No gener')
len(Genre)

100

In [156]:
#fetch Runtime
try:
    run=driver.find_elements_by_xpath('//p[@class="text-muted text-small"]//span[3]')
    for i in run:
        Run_time.append(i.text) 
except NoSuchElementException:
    Run_time.append('No runtime')
len(Run_time)

100

In [157]:
#fetch Ratings
try:
    rat=driver.find_elements_by_xpath('//div[1][@class="ipl-rating-star small"]/span[2]')
    for i in rat:
        Ratings.append(i.text) 
except NoSuchElementException: 
    Ratings.append('No Rating') 
len(Ratings)

100

In [158]:
#fetch Votes
try:
    vot=driver.find_elements_by_xpath('//p[4][@class="text-muted text-small"]/span[2]')
    for i in vot:
        Votes.append(i.text) 
except NoSuchElementException: 
    Votes.append('No vote') 
len(Votes)

100

In [159]:
IMDB_100=pd.DataFrame({})
IMDB_100['Name']=Name[:100]
IMDB_100['Year']=Year[:100]
IMDB_100['Genre']=Genre[:100]
IMDB_100['Run Time']=Run_time[:100]
IMDB_100['Ratings']=Ratings[:100]
IMDB_100['Votes']=Votes[:100]
IMDB_100

,Name,Year,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,847,075"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"884,797"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"885,203"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.6,"266,111"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"226,815"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"45,002"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"55,701"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8,"171,614"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"35,576"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"194,950"

In [241]:
#Question No 10 UCI Machine 
driver=webdriver.Chrome(r"C:\Users\INPshy\Downloads\chromedriver_win32\chromedriver.exe")

In [242]:
Url = 'https://archive.ics.uci.edu'
driver.get(Url)

In [243]:
#click on show all data
show=driver.find_element_by_xpath('/html/body/table[1]/tbody/tr/td[2]/span[2]/a/font/b')
show.click()

In [244]:
#create empty list to store dataset
Name=[]
Data=[]
Task=[]
Attribute=[]
No_of_instances=[]
No_of_attribute=[]
Year=[]

In [245]:
#fetch name
try:
    name=driver.find_elements_by_xpath('//table[@border="1"]/tbody/tr/td/table/tbody/tr/td/p/b') 
    for i in name:
        Name.append(i.text)
except NoSuchElementException:
    Name.append('no name') 
Name

['Abalone',
 'Adult',
 'Annealing',
 'Anonymous Microsoft Web Data',
 'Arrhythmia',
 'Artificial Characters',
 'Audiology (Original)',
 'Audiology (Standardized)',
 'Auto MPG',
 'Automobile',
 'Badges',
 'Balance Scale',
 'Balloons',
 'Breast Cancer',
 'Breast Cancer Wisconsin (Original)',
 'Breast Cancer Wisconsin (Prognostic)',
 'Breast Cancer Wisconsin (Diagnostic)',
 'Pittsburgh Bridges',
 'Car Evaluation',
 'Census Income',
 'Chess (King-Rook vs. King-Knight)',
 'Chess (King-Rook vs. King-Pawn)',
 'Chess (King-Rook vs. King)',
 'Chess (Domain Theories)',
 'Bach Chorales',
 'Connect-4',
 'Credit Approval',
 'Japanese Credit Screening',
 'Computer Hardware',
 'Contraceptive Method Choice',
 'Covertype',
 'Cylinder Bands',
 'Dermatology',
 'Diabetes',
 'DGP2 - The Second Data Generation Program',
 'Document Understanding',
 'EBL Domain Theories',
 'Echocardiogram',
 'Ecoli',
 'Flags',
 'Function Finding',
 'Glass Identification',
 "Haberman's Survival",
 'Hayes-Roth',
 'Heart Disease',
 'Hepatitis',
 'Horse Colic',
 'ICU',
 'Image Segmentation',
 'Internet Advertisements',
 'Ionosphere',
 'Iris',
 'ISOLET',
 'Kinship',
 'Labor Relations',
 'LED Display Domain',
 'Lenses',
 'Letter Recognition',
 'Liver Disorders',
 'Logic Theorist',
 'Lung Cancer',
 'Lymphography',
 'Mechanical Analysis',
 'Meta-data',
 'Mobile Robots',
 'Molecular Biology (Promoter Gene Sequences)',
 'Molecular Biology (Protein Secondary Structure)',
 'Molecular Biology (Splice-junction Gene Sequences)',
 "MONK's Problems",
 'Moral Reasoner',
 'Multiple Features',
 'Mushroom',
 'Musk (Version 1)',
 'Musk (Version 2)',
 'Nursery',
 'Othello Domain Theory',
 'Page Blocks Classification',
 'Optical Recognition of Handwritten Digits',
 'Pen-Based Recognition of Handwritten Digits',
 'Post-Operative Patient',
 'Primary Tumor',
 'Prodigy',
 'Qualitative Structure Activity Relationships',
 'Quadruped Mammals',
 'Servo',
 'Shuttle Landing Control',
 'Solar Flare',
 'Soybean (Large)',
 'Soybean (Small)',
 'Challenger USA Space Shuttle O-Ring',
 'Low Resolution Spectrometer',
 'Spambase',
 'SPECT Heart',
 'SPECTF Heart',
 'Sponge',
 'Statlog Project',
 'Student Loan Relational',
 'Teaching Assistant Evaluation',
 'Tic-Tac-Toe Endgame',
 'Thyroid Disease',
 'Trains',
 'University',
 'Congressional Voting Records',
 'Water Treatment Plant',
 'Waveform Database Generator (Version 1)',
 'Waveform Database Generator (Version 2)',
 'Wine',
 'Yeast',
 'Zoo',
 'Undocumented',
 'Twenty Newsgroups',
 'Australian Sign Language signs',
 'Australian Sign Language signs (High Quality)',
 'US Census Data (1990)',
 'Census-Income (KDD)',
 'Coil 1999 Competition Data',
 'Corel Image Features',
 'E. Coli Genes',
 'EEG Database',
 'El Nino',
 'Entree Chicago Recommendation Data',
 'CMU Face Images',
 'Insurance Company Benchmark (COIL 2000)',
 'Internet Usage Data',
 'IPUMS Census Database',
 'Japanese Vowels',
 'KDD Cup 1998 Data',
 'KDD Cup 1999 Data',
 'M. Tuberculosis Genes',
 'Movie',
 'MSNBC.com Anonymous Web Data',
 'NSF Research Award Abstracts 1990-2003',
 'Pioneer-1 Mobile Robot Data',
 'Pseudo Periodic Synthetic Time Series',
 'Reuters-21578 Text Categorization Collection',
 'Robot Execution Failures',
 'Synthetic Control Chart Time Series',
 'Syskill and Webert Web Page Ratings',
 'UNIX User Data',
 'Volcanoes on Venus - JARtool experiment',
 'Statlog (Australian Credit Approval)',
 'Statlog (German Credit Data)',
 'Statlog (Heart)',
 'Statlog (Landsat Satellite)',
 'Statlog (Image Segmentation)',
 'Statlog (Shuttle)',
 'Statlog (Vehicle Silhouettes)',
 'Connectionist Bench (Nettalk Corpus)',
 'Connectionist Bench (Sonar, Mines vs. Rocks)',
 'Connectionist Bench (Vowel Recognition - Deterding Data)',
 'Economic Sanctions',
 'Protein Data',
 'Cloud',
 'CalIt2 Building People Counts',
 'Dodgers Loop Sensor',
 'Poker Hand',
 'MAGIC Gamma Telescope',
 'UJI Pen Characters',
 'Mammographic Mass',
 'Forest Fires',
 'Reuters Transcribed Subset',
 'Bag of Words',
 'Concrete Compressive Strength',
 'Hill-Valley',
 'Arcene',
 'Dexter',
 'Dorothea',
 'Gisette',
 'Madelon',
 'Ozone Level Detection',
 'Abscisic Acid Signaling Network',
 'Parkinsons',
 'Character Trajectories',
 'Blood Transfusion Service Center',
 'UJI Pen Characters (Version 2)',
 'Semeion Handwritten Digit',
 'SECOM',
 'Plants',
 'Libras Movement',
 'Concrete Slump Test',
 'Communities and Crime',
 'Acute Inflammations',
 'Wine Quality',
 'URL Reputation',
 'p53 Mutants',
 'Parkinsons Telemonitoring',
 'Demospongiae',
 'Opinosis Opinion ⁄ Review',
 'Breast Tissue',
 'Cardiotocography',
 'Wall-Following Robot Navigation Data',
 'Spoken Arabic Digit',
 'Localization Data for Person Activity',
 'AutoUniv',
 'Steel Plates Faults',
 'MiniBooNE particle identification',
 'YearPredictionMSD',
 'PEMS-SF',
 'OpinRank Review Dataset',
 'Relative location of CT slices on axial axis',
 'Online Handwritten Assamese Characters Dataset',
 'PubChem Bioassay Data',
 'Record Linkage Comparison Patterns',
 'Communities and Crime Unnormalized',
 'Vertebral Column',
 'EMG Physical Action Data Set',
 'Vicon Physical Action Data Set',
 'Amazon Commerce reviews set',
 'Amazon Access Samples',
 'Reuter_50_50',
 'Farm Ads',
 'DBWorld e-mails',
 'KEGG Metabolic Relation Network (Directed)',
 'KEGG Metabolic Reaction Network (Undirected)',
 'Bank Marketing',
 'YouTube Comedy Slam Preference Data',
 'Gas Sensor Array Drift Dataset',
 'ILPD (Indian Liver Patient Dataset)',
 'OPPORTUNITY Activity Recognition',
 'Nomao',
 'SMS Spam Collection',
 'Skin Segmentation',
 'Planning Relax',
 'PAMAP2 Physical Activity Monitoring',
 'Restaurant & consumer data',
 'CNAE-9',
 'Individual household electric power consumption',
 'seeds',
 'Northix',
 'QtyT40I10D100K',
 'Legal Case Reports',
 'Human Activity Recognition Using Smartphones',
 'One-hundred plant species leaves data set',
 'Energy efficiency',
 'Yacht Hydrodynamics',
 'Fertility',
 'Daphnet Freezing of Gait',
 '3D Road Network (North Jutland, Denmark)',
 'ISTANBUL STOCK EXCHANGE',
 'Buzz in social media',
 'First-order theorem proving',
 'Wearable Computing: Classification of Body Postures and Movements (PUC-Rio)',
 'Gas sensor arrays in open sampling settings',
 'Climate Model Simulation Crashes',
 'MicroMass',
 'QSAR biodegradation',
 'BLOGGER',
 'Daily and Sports Activities',
 'User Knowledge Modeling',
 'Reuters RCV1 RCV2 Multilingual, Multiview Text Categorization Test collection',
 'NYSK',
 'Turkiye Student Evaluation',
 "ser Knowledge Modeling Data (Students' Knowledge Levels on DC Electrical Machines)",
 'EEG Eye State',
 'Physicochemical Properties of Protein Tertiary Structure',
 'seismic-bumps',
 'banknote authentication',
 'USPTO Algorithm Challenge, run by NASA-Harvard Tournament Lab and TopCoder Problem: Pat',
 'YouTube Multiview Video Games Dataset',
 'Gas Sensor Array Drift Dataset at Different Concentrations',
 'Activities of Daily Living (ADLs) Recognition Using Binary Sensors',
 'SkillCraft1 Master Table Dataset',
 'Weight Lifting Exercises monitored with Inertial Measurement Units',
 'SML2010',
 'Bike Sharing Dataset',
 'Predict keywords activities in a online social media',
 'Thoracic Surgery Data',
 'EMG dataset in Lower Limb',
 'SUSY',
 'HIGGS',
 'Qualitative_Bankruptcy',
 'LSVT Voice Rehabilitation',
 'Dataset for ADL Recognition with Wrist-worn Accelerometer',
 'Wilt',
 'User Identification From Walking Activity',
 'Activity Recognition from Single Chest-Mounted Accelerometer',
 'Leaf',
 'Dresses_Attribute_Sales',
 'Tamilnadu Electricity Board Hourly Readings',
 'Airfoil Self-Noise',
 'Wholesale customers',
 'Twitter Data set for Arabic Sentiment Analysis',
 'Combined Cycle Power Plant',
 'Urban Land Cover',
 'Diabetes 130-US hospitals for years 1999-2008',
 'Bach Choral Harmony',
 'StoneFlakes',
 'Tennis Major Tournament Match Statistics',
 'Parkinson Speech Dataset with Multiple Types of Sound Recordings',
 'Gesture Phase Segmentation',
 'Perfume Data',
 'BlogFeedback',
 'REALDISP Activity Recognition Dataset',
 'Newspaper and magazine images segmentation dataset',
 'AAAI 2014 Accepted Papers',
 'Gas sensor array under flow modulation',
 'Gas sensor array exposed to turbulent gas mixtures',
 'UJIIndoorLoc',
 'Sentence Classification',
 'Dow Jones Index',
 'sEMG for Basic Hand movements',
 'AAAI 2013 Accepted Papers',
 'Geographical Original of Music',
 'Condition Based Maintenance of Naval Propulsion Plants',
 'Grammatical Facial Expressions',
 'NoisyOffice',
 'MHEALTH Dataset',
 'Student Performance',
 'ElectricityLoadDiagrams20112014',
 'Gas sensor array under dynamic gas mixtures',
 'microblogPCU',
 'Firm-Teacher_Clave-Direction_Classification',
 'Dataset for Sensorless Drive Diagnosis',
 'TV News Channel Commercial Detection Dataset',
 'Phishing Websites',
 'Greenhouse Gas Observing Network',
 'Diabetic Retinopathy Debrecen Data Set',
 'HIV-1 protease cleavage',
 'Sentiment Labelled Sentences',
 'Online News Popularity',
 'Forest type mapping',
 'wiki4HE',
 'Online Video Characteristics and Transcoding Time Dataset',
 'Chronic_Kidney_Disease',
 'Machine Learning based ZZAlpha Ltd. Stock Recommendations 2012-2014',
 'Folio',
 'Taxi Service Trajectory - Prediction Challenge, ECML PKDD 2015',
 'Cuff-Less Blood Pressure Estimation',
 'Smartphone-Based Recognition of Human Activities and Postural Transitions',
 'Mice Protein Expression',
 'UJIIndoorLoc-Mag',
 'Heterogeneity Activity Recognition',
 'Educational Process Mining (EPM): A Learning Analytics Data Set',
 'HEPMASS',
 'Indoor User Movement Prediction from RSS data',
 'Open University Learning Analytics dataset',
 'default of credit card clients',
 'Mesothelioma’s disease data set',
 'Online Retail',
 'SIFT10M',
 'GPS Trajectories',
 'Detect Malacious Executable(AntiVirus)',
 'Occupancy Detection',
 'Improved Spiral Test Using Digitized Graphics Tablet for Monitoring Parkinson’s Disease',
 'News Aggregator',
 'Air Quality',
 'Twin gas sensor arrays',
 'Gas sensors for home activity monitoring',
 'Facebook Comment Volume Dataset',
 'Smartphone Dataset for Human Activity Recognition (HAR) in Ambient Assisted Living (AAL)',
 'Polish companies bankruptcy data',
 'Activity Recognition system based on Multisensor data fusion (AReM)',
 'Dota2 Games Results',
 'Facebook metrics',
 'UbiqLog (smartphone lifelogging)',
 'NIPS Conference Papers 1987-2015',
 'HTRU2',
 'Drug consumption (quantified)',
 'Appliances energy prediction',
 'Miskolc IIS Hybrid IPS',
 'KDC-4007 dataset Collection',
 'Geo-Magnetic field and WLAN dataset for indoor localisation from wristband and smartphone',
 'DrivFace',
 'Website Phishing',
 'YouTube Spam Collection',
 'Beijing PM2.5 Data',
 'Cargo 2000 Freight Tracking and Tracing',
 'Cervical cancer (Risk Factors)',
 'Quality Assessment of Digital Colposcopies',
 'KASANDR',
 'FMA: A Dataset For Music Analysis',
 'Air quality',
 'Epileptic Seizure Recognition',
 'Devanagari Handwritten Character Dataset',
 'Stock portfolio performance',
 'MoCap Hand Postures',
 'Early biomarkers of Parkinson�s disease based on natural connected speech',
 'Data for Software Engineering Teamwork Assessment in Education Setting',
 'PM2.5 Data of Five Chinese Cities',
 'Parkinson Disease Spiral Drawings Using Digitized Graphics Tablet',
 'Sales_Transactions_Dataset_Weekly',
 'Las Vegas Strip',
 'Eco-hotel',
 'MEU-Mobile KSD',
 'Crowdsourced Mapping',
 'gene expression cancer RNA-Seq',
 'Hybrid Indoor Positioning Dataset from WiFi RSSI, Bluetooth and magnetometer',
 'chestnut – LARVIC',
 'Burst Header Packet (BHP) flooding attack on Optical Burst Switching (OBS) Network',
 'Motion Capture Hand Postures',
 'Anuran Calls (MFCCs)',
 'TTC-3600: Benchmark dataset for Turkish text categorization',
 'Gastrointestinal Lesions in Regular Colonoscopy',
 'Daily Demand Forecasting Orders',
 'Paper Reviews',
 'extention of Z-Alizadeh sani dataset',
 'Z-Alizadeh Sani',
 'Dynamic Features of VirusShare Executables',
 'IDA2016Challenge',
 'DSRC Vehicle Communications',
 'Mturk User-Perceived Clusters over Images',
 'Character Font Images',
 'DeliciousMIL: A Data Set for Multi-Label Multi-Instance Learning with Instance Labels',
 'Autistic Spectrum Disorder Screening Data for Children',
 'Autistic Spectrum Disorder Screening Data for Adolescent',
 'APS Failure at Scania Trucks',
 'Wireless Indoor Localization',
 'HCC Survival',
 'CSM (Conventional and Social Media Movies) Dataset 2014 and 2015',
 'University of Tehran Question Dataset 2016 (UTQD.2016)',
 'Autism Screening Adult',
 'Activity recognition with healthy older people using a batteryless wearable sensor',
 'Immunotherapy Dataset',
 'Cryotherapy Dataset',
 'OCT data & Color Fundus Images of Left & Right Eyes',
 'Discrete Tone Image Dataset',
 'News Popularity in Multiple Social Media Platforms',
 'Ultrasonic flowmeter diagnostics',
 'ICMLA 2014 Accepted Papers Data Set',
 'BLE RSSI Dataset for Indoor localization and Navigation',
 'Container Crane Controller Data Set',
 'Residential Building Data Set',
 'Health News in Twitter',
 'chipseq',
 'SGEMM GPU kernel performance',
 'Repeat Consumption Matrices',
 'detection_of_IoT_botnet_attacks_N_BaIoT',
 'Absenteeism at work',
 'SCADI',
 'Condition monitoring of hydraulic systems',
 'Carbon Nanotubes',
 'Optical Interconnection Network',
 'Sports articles for objectivity analysis',
 'Breast Cancer Coimbra',
 'GNFUV Unmanned Surface Vehicles Sensor Data',
 'Dishonest Internet users Dataset',
 'Victorian Era Authorship Attribution',
 'Simulated Falls and Daily Living Activities Data Set',
 'Multimodal Damage Identification for Humanitarian Computing',
 'EEG Steady-State Visual Evoked Potential Signals',
 'Roman Urdu Data Set',
 'Avila',
 'PANDOR',
 'Drug Review Dataset (Druglib.com)',
 'Drug Review Dataset (Drugs.com)',
 'Physical Unclonable Functions',
 'Superconductivty Data',
 'WESAD (Wearable Stress and Affect Detection)',
 'GNFUV Unmanned Surface Vehicles Sensor Data Set 2',
 'Student Academics Performance',
 'Online Shoppers Purchasing Intention Dataset',
 'PMU-UD',
 "Parkinson's Disease Classification",
 'Electrical Grid Stability Simulated Data',
 'Caesarian Section Classification Dataset',
 'BAUM-1',
 'BAUM-2',
 'Audit Data',
 'BuddyMove Data Set',
 'Real estate valuation data set',
 'Early biomarkers of Parkinson’s disease based on natural connected speech Data Set',
 'Somerville Happiness Survey',
 '2.4 GHZ Indoor Channel Measurements',
 'EMG data for gestures',
 'Parking Birmingham',
 'Behavior of the urban traffic of the city of Sao Paulo in Brazil',
 'Travel Reviews',
 'Tarvel Review Ratings',
 'Rice Leaf Diseases',
 'Gas sensor array temperature modulation',
 'Facebook Live Sellers in Thailand',
 'Parkinson Dataset with replicated acoustic features',
 'Metro Interstate Traffic Volume',
 'Query Analytics Workloads Dataset',
 'Wave Energy Converters',
 'PPG-DaLiA',
 'Alcohol QCM Sensor Dataset',
 'Divorce Predictors data set',
 'Incident management process enriched event log',
 'Opinion Corpus for Lebanese Arabic Reviews (OCLAR)',
 'MEx',
 'Beijing Multi-Site Air-Quality Data',
 'Online Retail II',
 'Hepatitis C Virus (HCV) for Egyptian patients',
 'QSAR fish toxicity',
 'QSAR aquatic toxicity',
 'Human Activity Recognition from Continuous Ambient Sensor Data',
 'WISDM Smartphone and Smartwatch Activity and Biometrics Dataset',
 'QSAR oral toxicity',
 'QSAR androgen receptor',
 'QSAR Bioconcentration classes dataset',
 'QSAR fish bioconcentration factor (BCF)',
 'A study of Asian Religious and Biblical Texts',
 'Real-time Election Results: Portugal 2019',
 'Bias correction of numerical prediction model temperature forecast',
 'Bar Crawl: Detecting Heavy Drinking',
 'Kitsune Network Attack Dataset',
 'Shoulder Implant X-Ray Manufacturer Classification',
 'Speaker Accent Recognition',
 'Heart failure clinical records',
 'Deepfakes: Medical Image Tamper Detection',
 'selfBACK',
 'South German Credit',
 'Exasens',
 'Swarm Behaviour',
 'Crop mapping using fused optical-radar data set',
 'BitcoinHeistRansomwareAddressDataset',
 'Facebook Large Page-Page Network',
 'Amphibians',
 'Early stage diabetes risk prediction dataset.',
 'Turkish Spam V01',
 'Stock keeping units',
 'Demand Forecasting for a store',
 'Detect Malware Types',
 'Wave Energy Converters',
 'Youtube cookery channels viewers comments in Hinglish',
 'Pedestrian in Traffic Dataset',
 'Cervical Cancer Behavior Risk',
 'Sattriya_Dance_Single_Hand_Gestures Dataset',
 'Divorce Predictors data set',
 '3W dataset',
 'Malware static and dynamic features VxHeaven and Virus Total',
 'Internet Firewall Data',
 'User Profiling and Abusive Language Detection Dataset',
 'Estimation of obesity levels based on eating habits and physical condition',
 'Rice (Cammeo and Osmancik)',
 'Vehicle routing and scheduling problems',
 'Algerian Forest Fires Dataset',
 'Breath Metabolomics',
 'Horton General Hospital',
 'UrbanGB, urban road accidents coordinates labelled by the urban center',
 'Gas Turbine CO and NOx Emission Data Set',
 'Activity recognition using wearable physiological measurements',
 'clickstream data for online shopping',
 'CNNpred: CNN-based stock market prediction using a diverse set of variables',
 'Apartment for rent classified',
 ': Simulated Data set of Iraqi tourism places',
 'Nasarian CAD Dataset',
 'Monolithic Columns in Troad and Mysia Region',
 'Bar Crawl: Detecting Heavy Drinking',
 'Seoul Bike Sharing Demand',
 'Person Classification Gait Data',
 'Shill Bidding Dataset',
 'Iranian Churn Dataset',
 'Unmanned Aerial Vehicle (UAV) Intrusion Detection',
 'Bone marrow transplant: children',
 'Exasens',
 'COVID-19 Surveillance',
 'Refractive errors',
 'Shoulder Implant X-Ray Manufacturer Classification',
 'CLINC150',
 'HCV data',
 'Taiwanese Bankruptcy Prediction',
 'South German Credit (UPDATE)',
 'IIWA14-R820-Gazebo-Dataset-10Trajectories',
 'Guitar Chords finger positions',
 'Russian Corpus of Biographical Texts',
 'Codon usage',
 'Intelligent Media Accelerometer and Gyroscope (IM-AccGyro) Dataset',
 'Myocardial infarction complications',
 'Hungarian Chickenpox Cases',
 'Simulated data for survival modelling',
 'Student Performance on an entrance examination',
 'Chemical Composition of Ceramic Samples',
 'Labeled Text Forum Threads Dataset',
 'Stock keeping units',
 'BLE RSSI dataset for Indoor localization',
 'Basketball dataset',
 'GitHub MUSAE',
 'Anticancer peptides',
 'Monolithic Columns in Troad and Mysia Region',
 'Gender by Name',
 'Iranian Churn Dataset',
 'Unmanned Aerial Vehicle (UAV) Intrusion Detection',
 'Shoulder Implant Manufacture Classification',
 'LastFM Asia Social Network',
 'Wheat kernels',
 'Productivity Prediction of Garment Employees',
 'Multi-view Brain Networks',
 'LastFM Asia Social Network',
 'Wisesight Sentiment Corpus',
 'AI4I 2020 Predictive Maintenance Dataset',
 'Dry Bean Dataset',
 'in-vehicle coupon recommendation',
 'Gait Classification',
 'Wikipedia Math Essentials',
 'Wikipedia Math Essentials',
 'Synchronous Machine Data Set']

In [227]:
len(Name)

588

In [246]:
#fetch data types
try:
    data=driver.find_elements_by_xpath('//table[2][@border="1"]/tbody/tr/td[2]/p') 
    for i in data:
        Data.append(i.text)
except NoSuchElementException: 
    Data.append('no name')   
Data

['Data Types',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Univariate, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Data-Generator ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Univariate, Time-Series ',
 'Multivariate, Spatial ',
 'Multivariate ',
 'Multivariate, Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Data-Generator ',
 ' ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Relational ',
 'Multivariate ',
 'Multivariate, Data-Generator ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Sequential, Domain-Theory ',
 'Sequential ',
 'Sequential, Domain-Theory ',
 'Multivariate ',
 'Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Domain-Theory ',
 'Multivariate, Data-Generator ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Data-Generator ',
 'Multivariate, Data-Generator ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Text ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Relational ',
 'Multivariate, Time-Series ',
 'Spatio-temporal ',
 'Transactional, Sequential ',
 'Image ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Relational ',
 'Multivariate, Relational ',
 'Sequential ',
 'Text ',
 'Multivariate, Time-Series ',
 'Univariate, Time-Series ',
 'Text ',
 'Multivariate, Time-Series ',
 'Time-Series ',
 'Multivariate, Text ',
 'Text, Sequential ',
 'Image ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Domain-Theory ',
 ' ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Text ',
 'Multivariate ',
 'Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate, Time-Series ',
 'Univariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Text ',
 'Domain-Theory ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Time-Series ',
 'Time-Series ',
 'Multivariate, Text, Domain-Theory ',
 'Time-Series, Domain-Theory ',
 'Multivariate, Text, Domain-Theory ',
 'Text ',
 'Text ',
 'Multivariate, Univariate, Text ',
 'Multivariate, Univariate, Text ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Univariate ',
 'Multivariate, Text, Domain-Theory ',
 'Univariate ',
 'Univariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Univariate, Text ',
 'Sequential ',
 'Text ',
 'Multivariate, Time-Series ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Sequential, Text ',
 'Multivariate, Univariate, Time-Series ',
 'Time-Series, Multivariate ',
 'Multivariate ',
 'Sequential ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Multivariate, Text ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series, Text ',
 'Univariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 ' ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Univariate, Sequential, Time-Series ',
 'Univariate, Sequential, Time-Series ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Univariate, Domain-Theory ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 ' ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Text ',
 'Time-Series ',
 'Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate, Univariate, Sequential, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series, Domain-Theory ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series, Domain-Theory ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Text ',
 'Multivariate, Text ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Sequential, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 ' ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 ' ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Time-Series ',
 'Text ',
 ' ',
 ' ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Sequential, Text ',
 'Multivariate, Text ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 ' ',
 'Sequential ',
 'Univariate ',
 'Univariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Univariate, Domain-Theory ',
 'Multivariate ',
 'Text ',
 'Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Univariate ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Text ',
 'Time-Series ',
 'Multivariate, Text ',
 'Multivariate, Time-Series ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Univariate ',
 'Multivariate ',
 'Multivariate ',
 'Univariate ',
 'Time-Series ',
 'Time-Series ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate, Univariate, Sequential, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate, Text ',
 'Multivariate, Text ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Univariate ',
 'Multivariate, Sequential ',
 'Text ',
 'Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential, Time-Series, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate, Time-Series, Text ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series, Text ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate, Univariate ',
 'Multivariate ',
 'Multivariate, Univariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Univariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Text ',
 'Text ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Sequential, Time-Series ',
 'Time-Series ',
 'Multivariate ',
 'Sequential ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Time-Series ',
 'Time-Series ',
 'Multivariate ']

In [254]:
len(Data)

589

In [247]:
#fetch task
try:
    task=driver.find_elements_by_xpath('//table[2][@border="1"]/tbody/tr/td[3]/p') 
    for i in task:
        Task.append(i.text)
except NoSuchElementException:
    Task.append('no task')   
len(Task)

589

In [248]:
#fetch Attribute
try:
    attri=driver.find_elements_by_xpath('//table[@border="1"]/tbody/tr/td[4]') 
    for i in attri:
        Attribute.append(i.text)
except NoSuchElementException:
    Attribute.append('no attri')    
len(Attribute)

589

In [249]:
#fetch No of Instances
try:
    inst=driver.find_elements_by_xpath('//table[@border="1"]/tbody/tr/td[5]') 
    for i in inst:
        No_of_instances.append(i.text)
except NoSuchElementException:
    No_of_instances.append('no instances')   
len(No_of_instances)

589

In [250]:
#fetch No of Attribute
try:
    no_attri=driver.find_elements_by_xpath('//table[@border="1"]/tbody/tr/td[6]') 
    for i in no_attri:
        No_of_attribute.append(i.text)
except NoSuchElementException:
    No_of_attribute.append('no Attri')   
len(No_of_attribute)

589

In [251]:
#fetch Year
try:
    year=driver.find_elements_by_xpath('//table[@border="1"]/tbody/tr/td[7]') 
    for i in year:
        Year.append(i.text)
except NoSuchElementException:
    Year.append('no year')   
len(Year)

589

In [255]:
UCI=pd.DataFrame({})
UCI['Name']=Name[:588]
UCI['Data']=Data[1:589]
UCI['Task']=Task[1:589]
UCI['Attribute']=Attribute[1:589]
UCI['No of Instances']=No_of_instances[1:589]
UCI['No of Attribute']=No_of_attribute[1:589]
UCI['Year']=Year[1:589]
UCI

,Name,Data,Task,Attribute,No of Instances,No of Attribute,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
583,in-vehicle coupon recommendation,Multivariate,Classification,,12684,23,2020
584,Gait Classification,Multivariate,Classification,Real,48,321,2020
585,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
586,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
587,Synchronous Machine Data Set,Multivariate,Regression,Real,557,5,2021